# Generated by Django 2.2.10 on 2021-06-08 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('city', models.CharField(max_length=256)),
                ('score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Price_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_product_id', models.IntegerField()),
                ('merchant_id', models.IntegerField()),
                ('product_description', models.CharField(max_length=256)),
                ('remark', models.CharField(max_length=256)),
                ('price', models.IntegerField()),
                ('in_stock_status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Source_Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('price', models.IntegerField()),
                ('count_of_merchant', models.IntegerField()),
            ],
        ),
    ]
