# Generated by Django 2.2.10 on 2021-06-08 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='source_product',
            name='url_address',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
