# Generated by Django 2.2.10 on 2021-06-09 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_source_product_url_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source_product',
            name='url_address',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
