# Generated by Django 2.2.10 on 2021-06-09 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210609_0604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source_product',
            name='name',
            field=models.CharField(max_length=256),
        ),
    ]
