# Generated by Django 2.2.10 on 2021-06-09 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210609_0637'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test_project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=256)),
            ],
        ),
    ]
