# Generated by Django 2.2.10 on 2021-06-09 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_test_project'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test_project',
        ),
    ]
